// Deck registry — reads server/decks.json (generated by Unity DeckExporter)
// and applies it idempotently to the SQLite store.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const DEFAULT_REGISTRY_PATH = join(here, 'decks.json');

const REQUIRED_FIELDS = ['deckId', 'displayName', 'description', 'newCardsPerDay', 'cardIds'];

export function loadDeckRegistry(filePath = DEFAULT_REGISTRY_PATH) {
    let raw;
    try {
        raw = readFileSync(filePath, 'utf8');
    } catch (err) {
        throw new Error(`[registry] failed to read ${filePath}: ${err.message}`);
    }

    let parsed;
    try {
        parsed = JSON.parse(raw);
    } catch (err) {
        throw new Error(`[registry] malformed JSON in ${filePath}: ${err.message}`);
    }

    if (!Array.isArray(parsed)) {
        throw new Error(`[registry] expected top-level array in ${filePath}`);
    }

    for (const deck of parsed) {
        validateDeckSpec(deck, filePath);
    }
    return parsed;
}

function validateDeckSpec(deck, source) {
    if (!deck || typeof deck !== 'object') {
        throw new Error(`[registry] non-object deck entry in ${source}`);
    }
    for (const key of REQUIRED_FIELDS) {
        if (!(key in deck)) {
            throw new Error(`[registry] deck in ${source} missing field '${key}'`);
        }
    }
    if (typeof deck.deckId !== 'string' || deck.deckId.length === 0) {
        throw new Error(`[registry] invalid deckId in ${source}`);
    }
    if (!Array.isArray(deck.cardIds) || deck.cardIds.length === 0) {
        throw new Error(`[registry] deck '${deck.deckId}' must have non-empty cardIds[]`);
    }
    if (typeof deck.newCardsPerDay !== 'number' || deck.newCardsPerDay < 1) {
        throw new Error(`[registry] deck '${deck.deckId}' invalid newCardsPerDay`);
    }
}

export function applySeed(db, decks, nowIso = new Date().toISOString()) {
    const insertDeck = db.prepare(
        `INSERT INTO decks (deck_id, display_name, description, new_cards_per_day)
         VALUES (?, ?, ?, ?)
         ON CONFLICT(deck_id) DO UPDATE SET
           display_name = excluded.display_name,
           description = excluded.description,
           new_cards_per_day = excluded.new_cards_per_day`
    );
    const insertCard = db.prepare(
        `INSERT INTO cards (card_id, deck_id, ord) VALUES (?, ?, ?)
         ON CONFLICT(card_id) DO UPDATE SET
           deck_id = excluded.deck_id,
           ord = excluded.ord`
    );
    const insertSchedule = db.prepare(
        `INSERT OR IGNORE INTO card_schedules
           (card_id, reps, ease_factor, interval_days, due_at, stage, learning_step)
         VALUES (?, 0, 2.5, 0, ?, 'new', 0)`
    );

    const tx = db.transaction(() => {
        for (const deck of decks) {
            insertDeck.run(deck.deckId, deck.displayName, deck.description, deck.newCardsPerDay);
            for (let i = 0; i < deck.cardIds.length; i++) {
                const cardId = deck.cardIds[i];
                insertCard.run(cardId, deck.deckId, i + 1);
                insertSchedule.run(cardId, nowIso);
            }
        }
    });
    tx();
}

export function findOrphans(db, decks) {
    const expected = new Set();
    for (const deck of decks) {
        for (const cid of deck.cardIds) {
            expected.add(cid);
        }
    }
    const rows = db.prepare('SELECT card_id FROM cards').all();
    return rows.filter((r) => !expected.has(r.card_id)).map((r) => r.card_id);
}
